language: scala

scala:
  - 2.12.8

env:
  - SBT_OPTS="-Xmx4G"

script:
  - sbt coverage test coverageReport

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

