language: scala

scala:
  - 2.12.8

script:
  - sbt coverage test coverageReport

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.coursier"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: M045+ijEU1VsBlNuZYp01+Sy5pCUEEnbo7Syd0f5Ggp0dcCDMPZ2TewRNw58lPJivyK7dJ9EHX+YzUvVPMgge3u8b5S7CNJEjSnp7JJWkFzutCqqeblnD30CBiC9NxE5z7MciZrO9cYK9gZvyb57BPXVr38JGBylqUYqL14aIpXIbsVxmxtwKkTVmY4MpUMuAhXvU5KUZpyIzvdcitiBa+ndjJP/cJp9dopHKVrjoHnIS/Hv1toGF+cm/r5OG0AoS2XVfbiSZEKlKOXgQ7CkNIgbhvALjrzNjDlRKR5Kizhqqk6pi9WypMOGii+hbWXcPzikZlBLwPVYPSjYMXQQG5h6V9eNXc7iIDmN5/zMnw4+0wNkBBnP13GH+Wq0TsbLuoY9y/e3+1QYLzG3sUVlCkFbldUad97lbLWSEBVNiMM8BtxvTbCtiWdyr0rUR1j8N92sm2n1VUBfIc+w2KCsDWe1T1vCdJ99tThzPeneXobgqczBgGnOU4SBayC8VkLTh8kClIaoy7EgdO/CA9HJFFSlerb+VV09Ze+yoIpKakih3AFvjmgoAU1HWLl/s25XSbKsZ7EoZGLL6RALppVh58uIz9GqAtMbOosLBhZZBWSbsuTDVDFR++VM+N76mUJluwJxpnnrMSV5XWExOFsXqfR5gH1G4pPxIIC9dARsx60=
